config/routes.rb
Rails.application.routes.draw do
  resources :levels
  resources :tenants 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  namespace :api do 
    resources :tenants
    resources :levels 
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/level.rb
class Level < ApplicationRecord
  has_many :tenant_levels
  has_many :tenants, through: :tenant_levels
end

app/models/tenant.rb
class Tenant < ApplicationRecord
  belongs_to :level

  has_one_attached :photo

  scope :active, -> {where is_active: true}

  delegate :name, to: :level, prefix: :level
end

app/models/tenant_level.rb
class TenantLevel < ApplicationRecord
  belongs_to :tenant
  belongs_to :level
end

app/controllers/api/levels_controller.rb
class Api::LevelsController < ApplicationController
  def index
    @levels = Level.all
  end
end

app/controllers/api/tenants_controller.rb
class Api::TenantsController < ApplicationController 
  before_action :set_levels, only: [:index]
  def index
    @tenants = Tenant.active
  end

  private 
  
  def set_levels
    @levels = Level.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/levels_controller.rb
class LevelsController < ApplicationController
  before_action :set_level, only: %i[ show edit update destroy ]

  # GET /levels or /levels.json
  def index
    @levels = Level.all
  end

  # GET /levels/1 or /levels/1.json
  def show
  end

  # GET /levels/new
  def new
    @level = Level.new
  end

  # GET /levels/1/edit
  def edit
  end

  # POST /levels or /levels.json
  def create
    @level = Level.new(level_params)

    respond_to do |format|
      if @level.save
        format.html { redirect_to level_url(@level), notice: "Level was successfully created." }
        format.json { render :show, status: :created, location: @level }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @level.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /levels/1 or /levels/1.json
  def update
    respond_to do |format|
      if @level.update(level_params)
        format.html { redirect_to level_url(@level), notice: "Level was successfully updated." }
        format.json { render :show, status: :ok, location: @level }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @level.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /levels/1 or /levels/1.json
  def destroy
    @level.destroy

    respond_to do |format|
      format.html { redirect_to levels_url, notice: "Level was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_level
      @level = Level.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def level_params
      params.require(:level).permit(:name)
    end
end

app/controllers/tenants_controller.rb
class TenantsController < ApplicationController
  before_action :set_tenant, only: %i[ show edit update destroy ]
  before_action :set_levels, only: %i[ new edit]
  # GET /tenants or /tenants.json
  def index
    @tenants = Tenant.all
  end

  # GET /tenants/1 or /tenants/1.json
  def show
  end

  # GET /tenants/new
  def new
    @tenant = Tenant.new
  end

  # GET /tenants/1/edit
  def edit
  end

  # POST /tenants or /tenants.json
  def create
    @tenant = Tenant.new(tenant_params)

    respond_to do |format|
      if @tenant.save
        format.html { redirect_to tenant_url(@tenant), notice: "Tenant was successfully created." }
        format.json { render :show, status: :created, location: @tenant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tenant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tenants/1 or /tenants/1.json
  def update
    respond_to do |format|
      if @tenant.update(tenant_params)
        format.html { redirect_to tenant_url(@tenant), notice: "Tenant was successfully updated." }
        format.json { render :show, status: :ok, location: @tenant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tenant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tenants/1 or /tenants/1.json
  def destroy
    @tenant.destroy

    respond_to do |format|
      format.html { redirect_to tenants_url, notice: "Tenant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tenant
      @tenant = Tenant.find(params[:id])
    end

    def set_levels
      @levels = Level.all
    end

    # Only allow a list of trusted parameters through.
    def tenant_params
      params.require(:tenant).permit(:name, :description, :is_active, :unit_no, :photo, tenant_levels: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/helpers/tenants_helper.rb
module TenantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Directory</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/levels/_form.html.erb
<%= form_with(model: level) do |form| %>
  <% if level.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(level.errors.count, "error") %> prohibited this level from being saved:</h2>

      <ul>
        <% level.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/levels/_level.html.erb
<div id="<%= dom_id level %>">
  <p>
    <strong>Name:</strong>
    <%= level.name %>
  </p>

</div>

app/views/levels/edit.html.erb
<h1>Editing level</h1>

<%= render "form", level: @level %>

<br>

<div>
  <%= link_to "Show this level", @level %> |
  <%= link_to "Back to levels", levels_path %>
</div>

app/views/levels/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Levels</h1>

<div id="levels">
  <% @levels.each do |level| %>
    <%= render level %>
    <p>
      <%= link_to "Show this level", level %>
    </p>
  <% end %>
</div>

<%= link_to "New level", new_level_path %>

app/views/levels/new.html.erb
<h1>New level</h1>

<%= render "form", level: @level %>

<br>

<div>
  <%= link_to "Back to levels", levels_path %>
</div>

app/views/levels/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @level %>

<div>
  <%= link_to "Edit this level", edit_level_path(@level) %> |
  <%= link_to "Back to levels", levels_path %>

  <%= button_to "Destroy this level", @level, method: :delete %>
</div>

app/views/tenants/_form.html.erb
<%= form_with(model: tenant) do |form| %>
  <% if tenant.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tenant.errors.count, "error") %> prohibited this tenant from being saved:</h2>

      <ul>
        <% tenant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :levels, style: "display: block" %>
    <%= form.select :tenant_levels, options_from_collection_for_select(@levels, :id, :name, {selected: @tenant.tenant_levels.map(&:level_id)}), {}, {include_blank: false, size: 5, style: "width: 250px;"} %>
  </div>

  <div>
    <%= form.label :unit_no, style: "display: block" %>
    <%= form.text_field :unit_no %>
  </div>
  <div>
    <%= form.label :photo, style: "display: block"%>
    <%= form.file_field :photo %>
  </div>

  <div>
    <%= form.label :is_active, style: "display: block" %>
    <%= form.check_box :is_active %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tenants/_tenant.html.erb
<div id="<%= dom_id tenant %>">
  <p>
    <strong>Name:</strong>
    <%= tenant.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= tenant.description %>
  </p>

  <p>
    <strong>Is active:</strong>
    <%= tenant.is_active %>
  </p>

  <p>
    <strong>Unit no:</strong>
    <%= tenant.unit_no %>
  </p>

</div>

app/views/tenants/edit.html.erb
<h1>Editing tenant</h1>

<%= render "form", tenant: @tenant %>

<br>

<div>
  <%= link_to "Show this tenant", @tenant %> |
  <%= link_to "Back to tenants", tenants_path %>
</div>

app/views/tenants/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tenants</h1>

<div id="tenants">
  <% @tenants.each do |tenant| %>
    <%= render tenant %>
    <p>
      <%= link_to "Show this tenant", tenant %>
    </p>
  <% end %>
</div>

<%= link_to "New tenant", new_tenant_path %>

app/views/tenants/new.html.erb
<h1>New tenant</h1>

<%= render "form", tenant: @tenant %>

<br>

<div>
  <%= link_to "Back to tenants", tenants_path %>
</div>

app/views/tenants/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tenant %>

<div>
  <%= link_to "Edit this tenant", edit_tenant_path(@tenant) %> |
  <%= link_to "Back to tenants", tenants_path %>

  <%= button_to "Destroy this tenant", @tenant, method: :delete %>
</div>